---
- name: Compute safe veth interface names
  ansible.builtin.set_fact:
    router_veth_host: "v{{ router_name | hash('md5') | truncate(11, True, '') }}o"

- name: Delete router namespace and host-side veth
  osac.templates.agentless_net_network:
    action: delete_uplink
    namespace: "{{ router_name }}"
    host_interface: "{{ router_veth_host }}"
  become: true
